import {
  BarChart3,
  CalendarDays,
  Handshake,
  Instagram,
  LayoutDashboard,
  MapPin,
  Newspaper,
  Rss,
  Send,
  Settings,
  ClipboardCheck,
  Images,
  ListChecks,
} from "lucide-react";

export const navItems = [
  { to: "/dashboard", label: "Dashboard", icone: LayoutDashboard },
  { to: "/news", label: "Notícias", icone: Newspaper },
  { to: "/editorial", label: "Aprovação", icone: ClipboardCheck },
  { to: "/editorial/geografia", label: "Revisão de local", icone: MapPin },
  { to: "/feed", label: "Feed", icone: ListChecks },
  { to: "/posts", label: "Artes e posts", icone: Images },
  { to: "/publishing", label: "Fila de publicação", icone: Send },
  { to: "/calendar", label: "Calendário", icone: CalendarDays },
  { to: "/publications", label: "Publicações", icone: Send },
  { to: "/sponsors", label: "Patrocinadores", icone: Handshake },
  { to: "/sources", label: "Fontes", icone: Rss },
  { to: "/instagram", label: "Instagram", icone: Instagram },
  { to: "/analytics", label: "Analytics", icone: BarChart3 },
  { to: "/settings", label: "Configurações", icone: Settings },
] as const;
