/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminAnalyticsRouteImport } from './routes/_admin.analytics'
import { Route as AdminCalendarRouteImport } from './routes/_admin.calendar'
import { Route as AdminCommunityRouteImport } from './routes/_admin.community'
import { Route as AdminDashboardRouteImport } from './routes/_admin.dashboard'
import { Route as AdminFeedRouteImport } from './routes/_admin.feed'
import { Route as AdminInstagramRouteImport } from './routes/_admin.instagram'
import { Route as AdminPublicationsRouteImport } from './routes/_admin.publications'
import { Route as AdminPublishingRouteImport } from './routes/_admin.publishing'
import { Route as AdminSettingsRouteImport } from './routes/_admin.settings'
import { Route as AdminSourcesRouteImport } from './routes/_admin.sources'
import { Route as AdminEditorialIndexRouteImport } from './routes/_admin.editorial.index'
import { Route as AdminEditorialGeografiaRouteImport } from './routes/_admin.editorial.geografia'
import { Route as AdminNewsIndexRouteImport } from './routes/_admin.news.index'
import { Route as AdminNewsIdRouteImport } from './routes/_admin.news.$id'
import { Route as AdminPostsIndexRouteImport } from './routes/_admin.posts.index'
import { Route as AdminSponsorsIndexRouteImport } from './routes/_admin.sponsors.index'
import { Route as AdminSponsorsCampaignsRouteImport } from './routes/_admin.sponsors.campaigns'
import { Route as AdminSponsorsDeliverablesRouteImport } from './routes/_admin.sponsors.deliverables'
import { Route as ApiPublicHooksCollectNewsRouteImport } from './routes/api/public/hooks/collect-news'
import { Route as ApiPublicIntegrationsInstagramCallbackRouteImport } from './routes/api/public/integrations/instagram/callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCalendarRoute = AdminCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommunityRoute = AdminCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFeedRoute = AdminFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInstagramRoute = AdminInstagramRouteImport.update({
  id: '/instagram',
  path: '/instagram',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPublicationsRoute = AdminPublicationsRouteImport.update({
  id: '/publications',
  path: '/publications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPublishingRoute = AdminPublishingRouteImport.update({
  id: '/publishing',
  path: '/publishing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSourcesRoute = AdminSourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEditorialIndexRoute = AdminEditorialIndexRouteImport.update({
  id: '/editorial/',
  path: '/editorial/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEditorialGeografiaRoute = AdminEditorialGeografiaRouteImport.update({
  id: '/editorial/geografia',
  path: '/editorial/geografia',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNewsIndexRoute = AdminNewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNewsIdRoute = AdminNewsIdRouteImport.update({
  id: '/news/$id',
  path: '/news/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPostsIndexRoute = AdminPostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSponsorsIndexRoute = AdminSponsorsIndexRouteImport.update({
  id: '/sponsors/',
  path: '/sponsors/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSponsorsCampaignsRoute = AdminSponsorsCampaignsRouteImport.update({
  id: '/sponsors/campaigns',
  path: '/sponsors/campaigns',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSponsorsDeliverablesRoute =
  AdminSponsorsDeliverablesRouteImport.update({
    id: '/sponsors/deliverables',
    path: '/sponsors/deliverables',
    getParentRoute: () => AdminRoute,
  } as any)
const ApiPublicHooksCollectNewsRoute =
  ApiPublicHooksCollectNewsRouteImport.update({
    id: '/api/public/hooks/collect-news',
    path: '/api/public/hooks/collect-news',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicIntegrationsInstagramCallbackRoute =
  ApiPublicIntegrationsInstagramCallbackRouteImport.update({
    id: '/api/public/integrations/instagram/callback',
    path: '/api/public/integrations/instagram/callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/analytics': typeof AdminAnalyticsRoute
  '/calendar': typeof AdminCalendarRoute
  '/community': typeof AdminCommunityRoute
  '/dashboard': typeof AdminDashboardRoute
  '/feed': typeof AdminFeedRoute
  '/instagram': typeof AdminInstagramRoute
  '/publications': typeof AdminPublicationsRoute
  '/publishing': typeof AdminPublishingRoute
  '/settings': typeof AdminSettingsRoute
  '/sources': typeof AdminSourcesRoute
  '/editorial/geografia': typeof AdminEditorialGeografiaRoute
  '/news/$id': typeof AdminNewsIdRoute
  '/sponsors/campaigns': typeof AdminSponsorsCampaignsRoute
  '/sponsors/deliverables': typeof AdminSponsorsDeliverablesRoute
  '/editorial/': typeof AdminEditorialIndexRoute
  '/news/': typeof AdminNewsIndexRoute
  '/posts/': typeof AdminPostsIndexRoute
  '/sponsors/': typeof AdminSponsorsIndexRoute
  '/api/public/hooks/collect-news': typeof ApiPublicHooksCollectNewsRoute
  '/api/public/integrations/instagram/callback': typeof ApiPublicIntegrationsInstagramCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/analytics': typeof AdminAnalyticsRoute
  '/calendar': typeof AdminCalendarRoute
  '/community': typeof AdminCommunityRoute
  '/dashboard': typeof AdminDashboardRoute
  '/feed': typeof AdminFeedRoute
  '/instagram': typeof AdminInstagramRoute
  '/publications': typeof AdminPublicationsRoute
  '/publishing': typeof AdminPublishingRoute
  '/settings': typeof AdminSettingsRoute
  '/sources': typeof AdminSourcesRoute
  '/editorial/geografia': typeof AdminEditorialGeografiaRoute
  '/news/$id': typeof AdminNewsIdRoute
  '/sponsors/campaigns': typeof AdminSponsorsCampaignsRoute
  '/sponsors/deliverables': typeof AdminSponsorsDeliverablesRoute
  '/editorial': typeof AdminEditorialIndexRoute
  '/news': typeof AdminNewsIndexRoute
  '/posts': typeof AdminPostsIndexRoute
  '/sponsors': typeof AdminSponsorsIndexRoute
  '/api/public/hooks/collect-news': typeof ApiPublicHooksCollectNewsRoute
  '/api/public/integrations/instagram/callback': typeof ApiPublicIntegrationsInstagramCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/_admin/analytics': typeof AdminAnalyticsRoute
  '/_admin/calendar': typeof AdminCalendarRoute
  '/_admin/community': typeof AdminCommunityRoute
  '/_admin/dashboard': typeof AdminDashboardRoute
  '/_admin/feed': typeof AdminFeedRoute
  '/_admin/instagram': typeof AdminInstagramRoute
  '/_admin/publications': typeof AdminPublicationsRoute
  '/_admin/publishing': typeof AdminPublishingRoute
  '/_admin/settings': typeof AdminSettingsRoute
  '/_admin/sources': typeof AdminSourcesRoute
  '/_admin/editorial/geografia': typeof AdminEditorialGeografiaRoute
  '/_admin/news/$id': typeof AdminNewsIdRoute
  '/_admin/sponsors/campaigns': typeof AdminSponsorsCampaignsRoute
  '/_admin/sponsors/deliverables': typeof AdminSponsorsDeliverablesRoute
  '/_admin/editorial/': typeof AdminEditorialIndexRoute
  '/_admin/news/': typeof AdminNewsIndexRoute
  '/_admin/posts/': typeof AdminPostsIndexRoute
  '/_admin/sponsors/': typeof AdminSponsorsIndexRoute
  '/api/public/hooks/collect-news': typeof ApiPublicHooksCollectNewsRoute
  '/api/public/integrations/instagram/callback': typeof ApiPublicIntegrationsInstagramCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/analytics'
    | '/calendar'
    | '/community'
    | '/dashboard'
    | '/feed'
    | '/instagram'
    | '/publications'
    | '/publishing'
    | '/settings'
    | '/sources'
    | '/editorial/geografia'
    | '/news/$id'
    | '/sponsors/campaigns'
    | '/sponsors/deliverables'
    | '/editorial/'
    | '/news/'
    | '/posts/'
    | '/sponsors/'
    | '/api/public/hooks/collect-news'
    | '/api/public/integrations/instagram/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/analytics'
    | '/calendar'
    | '/community'
    | '/dashboard'
    | '/feed'
    | '/instagram'
    | '/publications'
    | '/publishing'
    | '/settings'
    | '/sources'
    | '/editorial/geografia'
    | '/news/$id'
    | '/sponsors/campaigns'
    | '/sponsors/deliverables'
    | '/editorial'
    | '/news'
    | '/posts'
    | '/sponsors'
    | '/api/public/hooks/collect-news'
    | '/api/public/integrations/instagram/callback'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/login'
    | '/_admin/analytics'
    | '/_admin/calendar'
    | '/_admin/community'
    | '/_admin/dashboard'
    | '/_admin/feed'
    | '/_admin/instagram'
    | '/_admin/publications'
    | '/_admin/publishing'
    | '/_admin/settings'
    | '/_admin/sources'
    | '/_admin/editorial/geografia'
    | '/_admin/news/$id'
    | '/_admin/sponsors/campaigns'
    | '/_admin/sponsors/deliverables'
    | '/_admin/editorial/'
    | '/_admin/news/'
    | '/_admin/posts/'
    | '/_admin/sponsors/'
    | '/api/public/hooks/collect-news'
    | '/api/public/integrations/instagram/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiPublicHooksCollectNewsRoute: typeof ApiPublicHooksCollectNewsRoute
  ApiPublicIntegrationsInstagramCallbackRoute: typeof ApiPublicIntegrationsInstagramCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/analytics': {
      id: '/_admin/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/calendar': {
      id: '/_admin/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AdminCalendarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/community': {
      id: '/_admin/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof AdminCommunityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/dashboard': {
      id: '/_admin/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/feed': {
      id: '/_admin/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AdminFeedRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/instagram': {
      id: '/_admin/instagram'
      path: '/instagram'
      fullPath: '/instagram'
      preLoaderRoute: typeof AdminInstagramRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/publications': {
      id: '/_admin/publications'
      path: '/publications'
      fullPath: '/publications'
      preLoaderRoute: typeof AdminPublicationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/publishing': {
      id: '/_admin/publishing'
      path: '/publishing'
      fullPath: '/publishing'
      preLoaderRoute: typeof AdminPublishingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/settings': {
      id: '/_admin/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/sources': {
      id: '/_admin/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof AdminSourcesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/editorial/': {
      id: '/_admin/editorial/'
      path: '/editorial'
      fullPath: '/editorial/'
      preLoaderRoute: typeof AdminEditorialIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/editorial/geografia': {
      id: '/_admin/editorial/geografia'
      path: '/editorial/geografia'
      fullPath: '/editorial/geografia'
      preLoaderRoute: typeof AdminEditorialGeografiaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/news/': {
      id: '/_admin/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof AdminNewsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/news/$id': {
      id: '/_admin/news/$id'
      path: '/news/$id'
      fullPath: '/news/$id'
      preLoaderRoute: typeof AdminNewsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/posts/': {
      id: '/_admin/posts/'
      path: '/posts'
      fullPath: '/posts/'
      preLoaderRoute: typeof AdminPostsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/sponsors/': {
      id: '/_admin/sponsors/'
      path: '/sponsors'
      fullPath: '/sponsors/'
      preLoaderRoute: typeof AdminSponsorsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/sponsors/campaigns': {
      id: '/_admin/sponsors/campaigns'
      path: '/sponsors/campaigns'
      fullPath: '/sponsors/campaigns'
      preLoaderRoute: typeof AdminSponsorsCampaignsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/sponsors/deliverables': {
      id: '/_admin/sponsors/deliverables'
      path: '/sponsors/deliverables'
      fullPath: '/sponsors/deliverables'
      preLoaderRoute: typeof AdminSponsorsDeliverablesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/hooks/collect-news': {
      id: '/api/public/hooks/collect-news'
      path: '/api/public/hooks/collect-news'
      fullPath: '/api/public/hooks/collect-news'
      preLoaderRoute: typeof ApiPublicHooksCollectNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/integrations/instagram/callback': {
      id: '/api/public/integrations/instagram/callback'
      path: '/api/public/integrations/instagram/callback'
      fullPath: '/api/public/integrations/instagram/callback'
      preLoaderRoute: typeof ApiPublicIntegrationsInstagramCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminCalendarRoute: typeof AdminCalendarRoute
  AdminCommunityRoute: typeof AdminCommunityRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminFeedRoute: typeof AdminFeedRoute
  AdminInstagramRoute: typeof AdminInstagramRoute
  AdminPublicationsRoute: typeof AdminPublicationsRoute
  AdminPublishingRoute: typeof AdminPublishingRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSourcesRoute: typeof AdminSourcesRoute
  AdminEditorialGeografiaRoute: typeof AdminEditorialGeografiaRoute
  AdminNewsIdRoute: typeof AdminNewsIdRoute
  AdminSponsorsCampaignsRoute: typeof AdminSponsorsCampaignsRoute
  AdminSponsorsDeliverablesRoute: typeof AdminSponsorsDeliverablesRoute
  AdminEditorialIndexRoute: typeof AdminEditorialIndexRoute
  AdminNewsIndexRoute: typeof AdminNewsIndexRoute
  AdminPostsIndexRoute: typeof AdminPostsIndexRoute
  AdminSponsorsIndexRoute: typeof AdminSponsorsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminCalendarRoute: AdminCalendarRoute,
  AdminCommunityRoute: AdminCommunityRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminFeedRoute: AdminFeedRoute,
  AdminInstagramRoute: AdminInstagramRoute,
  AdminPublicationsRoute: AdminPublicationsRoute,
  AdminPublishingRoute: AdminPublishingRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSourcesRoute: AdminSourcesRoute,
  AdminEditorialGeografiaRoute: AdminEditorialGeografiaRoute,
  AdminNewsIdRoute: AdminNewsIdRoute,
  AdminSponsorsCampaignsRoute: AdminSponsorsCampaignsRoute,
  AdminSponsorsDeliverablesRoute: AdminSponsorsDeliverablesRoute,
  AdminEditorialIndexRoute: AdminEditorialIndexRoute,
  AdminNewsIndexRoute: AdminNewsIndexRoute,
  AdminPostsIndexRoute: AdminPostsIndexRoute,
  AdminSponsorsIndexRoute: AdminSponsorsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiPublicHooksCollectNewsRoute: ApiPublicHooksCollectNewsRoute,
  ApiPublicIntegrationsInstagramCallbackRoute:
    ApiPublicIntegrationsInstagramCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
